[package]
name = "zeus-wavelet"
version.workspace = true
edition.workspace = true

[dependencies]
num-complex = "0.4"
rustfft = "6"
statrs = "0.18"
thiserror = "2"

[dev-dependencies]
rand = "0.9"
rand_distr = "0.5"
