[package]
name = "zeus-quantile-map"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = "2"
statrs = "0.18"
zeus-stats = { path = "../stats" }

[dev-dependencies]
approx = "0.5"
rand = "0.9"
rand_distr = "0.5"
