[package]
name = "zeus-markov"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = "2"
rand = "0.9"
zeus-stats = { path = "../stats" }
tracing.workspace = true

[dev-dependencies]
approx = "0.5"
rand = "0.9"
