[package]
name = "zeus-arma"
version.workspace = true
edition.workspace = true

[dependencies]
argmin = "0.11"
argmin-math = { version = "0.5", features = ["vec"] }
ndarray = "0.16"
rand = "0.9"
rand_distr = "0.5"
thiserror = "2"

[dev-dependencies]
approx = "0.5"
